language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.0
    - android-27
    - sys-img-x86-android-27
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

cache:
  directories:
    - $HOME/.gradle

before_script:
    - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"

script: "./gradlew clean build test -Dpre-dex=false"
